/**
 * The LeetCode Ladder, modelled on the Codeforces "CP-31" sheet:
 *   - fixed-size levels (31 problems each), grouped by DIFFICULTY RATING, not by topic
 *   - you work through a level, then climb to the next one
 *   - progress is a checklist
 *
 * LeetCode has no official problem ratings. Ratings come from the community project
 * zerotrac/leetcode_problem_rating (MIT), which estimates Elo-style ratings for Weekly and
 * Biweekly contest problems. Level 0 ("Foundations") is a hand-picked list of classic problems
 * for people who are not ready for contest problems yet.
 *
 * The level data lives in data/ladder.json and is generated by `npm run ladder:build`.
 */
import ladderData from "../../data/ladder.json";
import { COMPLETE_RATIO, type LadderFile, type LadderLevel, type LadderProblem } from "./ladderBuild";

export { COMPLETE_RATIO, PER_LEVEL, buildRatedLevels, contestCode, spreadEvenly } from "./ladderBuild";
export type { LadderFile, LadderLevel, LadderProblem, RatingRow } from "./ladderBuild";


export const LADDER: LadderFile = ladderData as LadderFile;

/* ------------------------------------------------------------------ progress */

export interface LevelProgress {
  level: LadderLevel;
  solved: number;
  total: number;
  ratio: number;
  complete: boolean;
}

export function levelProgress(level: LadderLevel, solved: ReadonlySet<string>): LevelProgress {
  const total = level.problems.length;
  const done = level.problems.filter((p) => solved.has(p.slug)).length;
  const ratio = total ? done / total : 0;
  return { level, solved: done, total, ratio, complete: total > 0 && done >= Math.ceil(total * COMPLETE_RATIO) };
}

export function allProgress(solved: ReadonlySet<string>, ladder: LadderFile = LADDER): LevelProgress[] {
  return ladder.levels.map((l) => levelProgress(l, solved));
}

/** First level at or above `startLevel` that is not yet complete (the last level if all are). */
export function currentLevelId(progress: LevelProgress[], startLevel: number): number {
  const from = Math.min(Math.max(0, startLevel), progress.length - 1);
  const open = progress.slice(from).find((p) => !p.complete);
  return (open ?? progress[progress.length - 1]).level.id;
}

/** The next unsolved problems of a level, in ladder order. */
export function nextUp(level: LadderLevel, solved: ReadonlySet<string>, count = 3): LadderProblem[] {
  return level.problems.filter((p) => !solved.has(p.slug)).slice(0, count);
}

/**
 * Where to start if the user hasn't chosen: a rough contest-rating guess from their
 * difficulty counts, minus a comfort margin (CP-31 advises starting a little below your level).
 */
export function suggestStartLevel(counts: { easy: number; medium: number; hard: number }, ladder: LadderFile = LADDER): number {
  const total = counts.easy + counts.medium + counts.hard;
  if (total < 80 || counts.medium < 25) return 0; // Foundations first
  const estimate = 1000 + 2 * counts.medium + 6 * counts.hard;
  const target = Math.max(1100, Math.round((estimate - 300) / 100) * 100);
  let best = 1;
  for (const l of ladder.levels) if (l.minRating !== null && l.minRating <= target) best = l.id;
  return best;
}

export { ratingTier, type RatingTier } from "./tier";
